import { IconDefinition } from '@fortawesome/fontawesome-svg-core';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
    faApple, faLinkedin, faGithub, faWhatsapp, faFacebook, faXTwitter, faTelegram,
} from '@fortawesome/free-brands-svg-icons';
import {
    faLayerGroup, faMap, faMapMarkerAlt, faLocationDot, faMapPin, faDrawPolygon,
    faXmark, faBars, faUsers,
    faChevronLeft, faChevronRight, faChevronUp, faChevronDown,
    faEye, faEyeSlash, faDownload, faList, faFilter, faTableColumns,
    faMagnifyingGlass, faTable, faShareNodes, faCopy, faCheck, faQrcode,
    faFilePdf, faBook, faEllipsisVertical,
    faStar, faFlag, faCrosshairs, faCompass, faCircle, faCircleDot, faSignsPost,
    faCar, faBus, faBicycle, faMotorcycle, faTruck, faTrain, faPlane, faHelicopter,
    faShip, faTaxi, faGasPump, faParking, faTrafficLight, faRoad, faRoute,
    faTruckMedical, faPersonBiking, faPersonHiking, faPlug,
    faHospital, faHouseMedical, faPills, faHeartPulse, faSyringe, faStethoscope,
    faWheelchair, faCross, faKitMedical, faPersonCane,
    faSchool, faBuildingColumns, faGraduationCap, faChalkboardUser, faMicroscope,
    faBookOpen, faPencil,
    faUtensils, faMugHot, faStore, faCartShopping, faBed, faLandmark, faEnvelope,
    faScissors, faWrench, faCity, faBuilding, faIndustry, faWarehouse,
    faShieldHalved, faFireExtinguisher, faLifeRing, faTriangleExclamation,
    faBell, faPersonShelter, faVault,
    faFutbol, faDumbbell, faMasksTheater, faCamera, faPersonSwimming, faMountainSun,
    faTree, faMusic, faPanorama,
    faChurch, faPlaceOfWorship, faChessRook,
    faBolt, faDroplet, faTowerBroadcast, faSolarPanel, faRecycle, faWater,
    faLeaf, faFire, faSatellite,
    faCircleExclamation, faCircleInfo, faCircleQuestion, faBan, faCircleCheck,
    faArrowUp, faArrowRight,
} from '@fortawesome/free-solid-svg-icons';

export const Icons: Record<string, IconDefinition> = {
    faLayerGroup, faMap, faMapMarkerAlt, faLocationDot, faMapPin, faDrawPolygon,
    faRoad, faRoute, faTree, faWater, faBuildingColumns, faBuilding, faPanorama,
    faSatellite, faCity, faIndustry, faHospital, faSchool, faChurch, faLandmark,
    faParking, faFutbol, faPersonBiking, faPersonHiking,
    faStar, faFlag, faCrosshairs, faCompass, faCircle, faCircleDot, faSignsPost,
    faCar, faBus, faBicycle, faMotorcycle, faTruck, faTrain, faPlane, faHelicopter,
    faShip, faTaxi, faGasPump, faTrafficLight, faTruckMedical, faPlug,
    faHouseMedical, faPills, faHeartPulse, faSyringe, faStethoscope, faWheelchair,
    faCross, faKitMedical, faPersonCane,
    faGraduationCap, faChalkboardUser, faMicroscope, faBookOpen, faPencil, faBook,
    faUtensils, faMugHot, faStore, faCartShopping, faBed, faEnvelope,
    faScissors, faWrench, faWarehouse,
    faShieldHalved, faFireExtinguisher, faLifeRing, faTriangleExclamation,
    faBell, faPersonShelter, faVault,
    faDumbbell, faMasksTheater, faCamera, faPersonSwimming, faMountainSun, faMusic,
    faPlaceOfWorship, faChessRook,
    faBolt, faDroplet, faTowerBroadcast, faSolarPanel, faRecycle, faLeaf, faFire,
    faCircleExclamation, faCircleInfo, faCircleQuestion, faBan, faCircleCheck,
    faArrowUp, faArrowRight,
};

export {
    FontAwesomeIcon,
    faApple, faLinkedin, faGithub, faWhatsapp, faFacebook, faXTwitter, faTelegram,
    faLayerGroup, faMap, faMapMarkerAlt, faLocationDot, faMapPin, faDrawPolygon,
    faXmark, faBars, faUsers,
    faChevronLeft, faChevronRight, faChevronUp, faChevronDown,
    faEye, faEyeSlash, faDownload, faList, faFilter, faTableColumns,
    faMagnifyingGlass, faTable, faShareNodes, faCopy, faCheck, faQrcode,
    faFilePdf, faBook, faEllipsisVertical,
    faStar, faFlag, faCrosshairs, faCompass, faCircle, faCircleDot, faSignsPost,
    faCar, faBus, faBicycle, faMotorcycle, faTruck, faTrain, faPlane, faHelicopter,
    faShip, faTaxi, faGasPump, faParking, faTrafficLight, faRoad, faRoute,
    faTruckMedical, faPersonBiking, faPersonHiking, faPlug,
    faHospital, faHouseMedical, faPills, faHeartPulse, faSyringe, faStethoscope,
    faWheelchair, faCross, faKitMedical, faPersonCane,
    faSchool, faBuildingColumns, faGraduationCap, faChalkboardUser, faMicroscope,
    faBookOpen, faPencil,
    faUtensils, faMugHot, faStore, faCartShopping, faBed, faLandmark, faEnvelope,
    faScissors, faWrench, faCity, faBuilding, faIndustry, faWarehouse,
    faShieldHalved, faFireExtinguisher, faLifeRing, faTriangleExclamation,
    faBell, faPersonShelter, faVault,
    faFutbol, faDumbbell, faMasksTheater, faCamera, faPersonSwimming, faMountainSun,
    faTree, faMusic, faPanorama,
    faChurch, faPlaceOfWorship, faChessRook,
    faBolt, faDroplet, faTowerBroadcast, faSolarPanel, faRecycle, faWater,
    faLeaf, faFire, faSatellite,
    faCircleExclamation, faCircleInfo, faCircleQuestion, faBan, faCircleCheck,
    faArrowUp, faArrowRight,
};
