# -*- coding: utf-8 -*-
"""
Generates the Vite + React + OpenLayers + Tailwind WebGIS project
from the templates/ directory, substituting dynamic placeholders.
"""
import os
import json
import shutil
import re
from datetime import datetime


# Icons map: layer label keywords → FontAwesome icon name
_ICON_RULES = [
    (['edif', 'build', 'construc', 'casa', 'imóvel'],   'faBuilding'),
    (['lot', 'parcel', 'cadastr', 'quadra', 'polígono'], 'faDrawPolygon'),
    (['rua', 'road', 'logradour', 'eixo', 'via', 'avenida'], 'faRoad'),
    (['route', 'trecho', 'caminho', 'trilha'],           'faRoute'),
    (['vegeta', 'verde', 'arvore', 'tree', 'floresta'],  'faTree'),
    (['agua', 'water', 'hidro', 'piscina', 'rio', 'lago'], 'faWater'),
    (['orto', 'foto', 'imagem', 'raster', 'panoram'],    'faPanorama'),
    (['satélite', 'satelite', 'spot', 'sentinel'],       'faSatellite'),
]
_GEOM_ICON = {
    'polygon': 'faDrawPolygon',
    'line':    'faRoad',
    'point':   'faLocationDot',
}


def _icon_for(layer: dict) -> str:
    name = (layer.get('label') or '').lower()
    for keywords, icon in _ICON_RULES:
        if any(k in name for k in keywords):
            return icon
    return _GEOM_ICON.get(layer.get('geometryType', 'polygon'), 'faLayerGroup')


class WebGISGenerator:
    """
    Copies the WebGIS template tree to *output_dir* and resolves all
    {{PLACEHOLDER}} tokens in the dynamic files.
    """

    # Files that contain placeholders and must be processed
    _DYNAMIC = {
        'src/pages/Home.tsx',
        'src/components/Sidebar.tsx',
        'src/components/Header.tsx',
        'src/components/ShareMenu.tsx',
        'src/components/ReportsMenu.tsx',
        'index.html',
    }

    def __init__(self, templates_dir: str, output_dir: str, config: dict):
        self.templates_dir = templates_dir
        self.output_dir = output_dir
        self.config = config

    # ─────────────────────────────────────────────────────────
    # Public API
    # ─────────────────────────────────────────────────────────

    def generate(self):
        self._copy_templates()
        self._process_dynamic_files()
        self._write_config_ts()
        self._write_geodata_ts()
        self._write_readme()
        os.makedirs(
            os.path.join(self.output_dir, 'public', 'Produtos'),
            exist_ok=True,
        )
        # Create report subfolders referenced by the user
        for r in self.config.get('reports', []):
            folder = r.get('folder', 'Relatorios')
            if folder:
                os.makedirs(
                    os.path.join(self.output_dir, 'public', folder),
                    exist_ok=True,
                )

    # ─────────────────────────────────────────────────────────
    # Write config.ts directly (bypass Prettier placeholder corruption)
    # ─────────────────────────────────────────────────────────

    def _write_config_ts(self):
        """Write src/config.ts from Python — never touched by Prettier."""
        cfg = self.config
        lon = cfg['center'][0]
        lat = cfg['center'][1]
        zoom = cfg.get('zoom', 18)
        title = cfg['title'].replace("'", "\\'")
        subtitle = cfg.get('subtitle', '').replace("'", "\\'")
        basemaps = self._basemaps_array()
        content = (
            '// Generated by UFPR Map Composer QGIS Plugin — do not edit manually.\n'
            f'export const MAP_CENTER: [number, number] = [{lon}, {lat}];\n'
            f'export const MAP_ZOOM = {zoom};\n'
            f"export const PROJECT_TITLE = '{title}';\n"
            f"export const PROJECT_SUBTITLE = '{subtitle}';\n"
            '\n'
            'export interface BasemapConfig {\n'
            '    id: string;\n'
            '    label: string;\n'
            '    url: string;\n'
            '    attribution: string;\n'
            '    default: boolean;\n'
            '}\n'
            '\n'
            f'export const BASEMAPS: BasemapConfig[] = {basemaps};\n'
            '\n'
            'export interface FieldConfig { key: string; label: string; defaultHidden?: boolean; }\n'
        )
        out_path = os.path.join(self.output_dir, 'src', 'config.ts')
        with open(out_path, 'w', encoding='utf-8') as fh:
            fh.write(content)

    # ─────────────────────────────────────────────────────────
    # Embed GeoJSON as TypeScript (no server needed)
    # ─────────────────────────────────────────────────────────

    def _write_geodata_ts(self):
        """Write src/data/geodata.ts embedding all exported GeoJSONs inline."""
        lines = [
            '// Auto-generated by UFPR Map Composer. Do not edit.',
            '// eslint-disable-next-line @typescript-eslint/no-explicit-any',
            'const GEODATA: Record<string, any> = {',
        ]
        for layer in self.config['layers']:
            geojson_path = os.path.join(
                self.output_dir, 'public', 'Produtos', layer['file']
            )
            if os.path.exists(geojson_path):
                with open(geojson_path, 'r', encoding='utf-8') as fh:
                    data = fh.read().strip()
                lines.append(f"  '{layer['id']}': {data},")
            else:
                lines.append(
                    f"  '{layer['id']}': "
                    '{"type":"FeatureCollection","features":[]},'
                )
        lines += ['};', 'export default GEODATA;']
        out_path = os.path.join(self.output_dir, 'src', 'data', 'geodata.ts')
        os.makedirs(os.path.dirname(out_path), exist_ok=True)
        with open(out_path, 'w', encoding='utf-8') as fh:
            fh.write('\n'.join(lines) + '\n')

    # ─────────────────────────────────────────────────────────
    # Template copying
    # ─────────────────────────────────────────────────────────

    def _copy_templates(self):
        for root, dirs, files in os.walk(self.templates_dir):
            for filename in files:
                src_path = os.path.join(root, filename)
                rel_path = os.path.relpath(src_path, self.templates_dir)

                # Rename the gitignore stub
                if filename == '_gitignore':
                    rel_path = rel_path.replace('_gitignore', '.gitignore')

                dst_path = os.path.join(self.output_dir, rel_path)
                os.makedirs(os.path.dirname(dst_path), exist_ok=True)
                shutil.copy2(src_path, dst_path)

    # ─────────────────────────────────────────────────────────
    # Placeholder substitution
    # ─────────────────────────────────────────────────────────

    def _process_dynamic_files(self):
        replacements = self._build_replacements()
        # Regex that matches {{ PLACEHOLDER }} with any surrounding spaces
        _norm = re.compile(r'\{\{\s*([A-Z_]+)\s*\}\}')
        for rel in self._DYNAMIC:
            path = os.path.join(self.output_dir, rel)
            if not os.path.exists(path):
                continue
            with open(path, 'r', encoding='utf-8') as fh:
                content = fh.read()
            # Normalize any {{ X }} → {{X}} so formatters can't break things
            content = _norm.sub(r'{{\1}}', content)
            for placeholder, value in replacements.items():
                content = content.replace(placeholder, value)
            with open(path, 'w', encoding='utf-8') as fh:
                fh.write(content)

    def _build_replacements(self) -> dict:
        cfg = self.config
        return {
            '{{PAGE_TITLE}}':           cfg['title'],
            '{{PAGE_SUBTITLE}}':        cfg['subtitle'],
            '{{BASE_PATH}}':            cfg.get('base_path', '/'),
            '{{CENTER_LON}}':           str(cfg['center'][0]),
            '{{CENTER_LAT}}':           str(cfg['center'][1]),
            '{{INITIAL_ZOOM}}':         str(cfg.get('zoom', 18)),
            '{{LAYERS_ARRAY}}':         self._layers_array(),
            '{{DEFAULT_VISIBLE_SET}}':  self._default_visible_set(),
            '{{LAYER_ICON_IMPORTS}}':   self._layer_icon_imports(),
            '{{BASEMAPS_ARRAY}}':       self._basemaps_array(),
            '{{ALUNOS_ARRAY}}':         self._alunos_array(),
            '{{REPORTS_ARRAY}}':        self._reports_array(),
            '{{COPYRIGHT_TEXT}}':       (
                f"© {datetime.now().year} "
                f"{cfg.get('title', 'WebGIS')}"
            ),
            '{{SHARE_TITLE}}':          cfg['title'],
        }

    # ─────────────────────────────────────────────────────────
    # TypeScript snippet generators
    # ─────────────────────────────────────────────────────────

    def _layers_array(self) -> str:
        lines = []
        for layer in self.config['layers']:
            icon = _icon_for(layer)
            label = layer['label'].replace("'", "\\'")
            file_name = layer.get('file', '')
            # Serialize popup fields
            fields = layer.get('fields', [])
            if fields:
                fields_js = '[' + ', '.join(
                    f"{{key:'{f['key'].replace(chr(39), chr(92)+chr(39))}'"
                    f",label:'{f['label'].replace(chr(39), chr(92)+chr(39))}'"
                    f",defaultHidden:{str(f.get('defaultHidden', False)).lower()}}}"
                    for f in fields
                ) + ']'
            else:
                fields_js = '[]'
            lines.append(
                f"  {{ id: '{layer['id']}', label: '{label}', "
                f"file: '{file_name}', color: '{layer['color']}', "
                f"geometryType: '{layer.get('geometryType', 'polygon')}', "
                f"visible: {str(layer.get('visible', True)).lower()}, "
                f"fields: {fields_js}, "
                f"icon: {icon} }},"
            )
        return '\n'.join(lines)

    def _layer_icon_imports(self) -> str:
        """Collect the unique icon names used and return a comma-separated import list."""
        icons = sorted({_icon_for(l) for l in self.config['layers']})
        if not icons:
            icons = ['faLayerGroup']
        return ',\n  '.join(icons)

    def _default_visible_set(self) -> str:
        ids = [
            f"'{l['id']}'"
            for l in self.config['layers']
            if l.get('visible', True)
        ]
        return ', '.join(ids)

    def _basemaps_array(self) -> str:
        basemaps = self.config.get('basemaps', [])
        if not basemaps:
            # Fallback: OSM only
            return (
                "[\n"
                "  { id: 'osm', label: 'OpenStreetMap', "
                "url: 'https://{a-c}.tile.openstreetmap.org/{z}/{x}/{y}.png', "
                "attribution: '© OpenStreetMap contributors', default: true },\n"
                "]"
            )
        lines = []
        for bm in basemaps:
            label = bm['label'].replace("'", "\\'")
            url = bm['url'].replace("'", "\\'")
            attr = bm['attribution'].replace("'", "\\'")
            is_default = 'true' if bm.get('default') else 'false'
            lines.append(
                f"  {{ id: '{bm['id']}', label: '{label}', "
                f"url: '{url}', attribution: '{attr}', default: {is_default} }},"
            )
        return '[\n' + '\n'.join(lines) + '\n]'

    def _reports_array(self) -> str:
        reports = self.config.get('reports', [])
        if not reports:
            return '[]'
        items = []
        for r in reports:
            label = r['label'].replace("'", "\\'")
            file_ = r['file'].replace("'", "\\'")
            folder = r.get('folder', 'Relatorios').replace("'", "\\'")
            items.append(
                f"  {{ label: '{label}', file: '{file_}', folder: '{folder}' }},"
            )
        return '[\n' + '\n'.join(items) + '\n]'

    def _alunos_array(self) -> str:
        if not self.config.get('team'):
            return '[]'
        items = []
        for member in self.config['team']:
            name = member['name'].replace("'", "\\'")
            linkedin = member.get('linkedin', '')
            initials = '+'.join(name.split()[:2]) if name else 'U'
            foto = (
                f'https://ui-avatars.com/api/?name={initials}'
                '&background=1a1a1a&color=fff&bold=true&size=128'
            )
            items.append(
                f"  {{ nome: '{name}', linkedin: '{linkedin}', foto: '{foto}' }},"
            )
        return '[\n' + '\n'.join(items) + '\n]'

    # ─────────────────────────────────────────────────────────
    # README
    # ─────────────────────────────────────────────────────────

    def _write_readme(self):
        title = self.config['title']
        base = self.config.get('base_path', '/')
        layers_list = '\n'.join(
            f"- **{l['label']}** (`{l['file']}`)"
            for l in self.config['layers']
        )
        content = f"""# {title} — WebGIS

Projeto gerado automaticamente pelo **UFPR Map Composer** QGIS Plugin.

## Camadas incluídas

{layers_list}

## Desenvolvimento local

```bash
npm install
npm run dev
```

Abra http://localhost:5173{base}

## Build para produção

```bash
npm run build
```

Os arquivos estáticos serão gerados em `dist/`.

## Deploy no GitHub Pages

1. Crie um repositório no GitHub
2. Configure o campo **Caminho base** no plugin com `/NOME-DO-REPO/`
3. Execute os comandos abaixo:

```bash
git init
git add .
git commit -m "Initial WebGIS commit"
git remote add origin https://github.com/USUARIO/REPO.git
git push -u origin main
```

4. Nas configurações do repositório → **Pages** → selecione a branch `main`
5. Configure o GitHub Action (`.github/workflows/deploy.yml`) para build automático

## Stack

- **Mapa:** [OpenLayers 10](https://openlayers.org/)
- **Framework:** [React 19](https://react.dev/) + [TypeScript](https://www.typescriptlang.org/)
- **Build:** [Vite 8](https://vitejs.dev/)
- **Estilos:** [Tailwind CSS 4](https://tailwindcss.com/)
- **UI:** Glassmorphism (Apple-inspired)
- **Projeção de coordenadas:** proj4js (UTM / SIRGAS 2000)

---

Gerado pelo plugin **UFPR Map Composer** em {datetime.now().strftime('%Y-%m-%d %H:%M')}.
"""
        readme_path = os.path.join(self.output_dir, 'README.md')
        with open(readme_path, 'w', encoding='utf-8') as fh:
            fh.write(content)
