// Generated by UFPR Map Composer QGIS Plugin — do not edit manually.
// This file is overwritten by generator.py — edits here are ignored.
export const MAP_CENTER: [number, number] = [0, 0];
export const MAP_ZOOM = 15;
export const MAP_ZOOM_MIN = 5;
export const MAP_ZOOM_MAX = 22;
export const PROJECT_TITLE = '';
export const PROJECT_SUBTITLE = '';
export const COMPARE_MODE = false;
export const COMPARE_LEFT_TITLE = 'Mapa A';
export const COMPARE_RIGHT_TITLE = 'Mapa B';
export const SHOW_DOCS = true;
export const SHOW_SHARE = true;
export const SHOW_TEAM = true;

export interface BasemapConfig {
    id: string;
    label: string;
    url: string;
    attribution: string;
    default: boolean;
}

export const BASEMAPS: BasemapConfig[] = [];

export interface FieldConfig { key: string; label: string; defaultHidden?: boolean; }
